const axios = require('axios');
const config = require('../config/config');
const fs = require('fs');
const path = require('path');

function toGaul(text, language = 'id') {
    if (language !== 'id') return text; // Hanya terapkan untuk bahasa Indonesia

    const gaulDict = {
        'saya': 'gue',
        'aku': 'gue',
        'kamu': 'lo',
        'anda': 'elo',
        'anda bisa': 'lo bisa',
        'bagaimana': 'gimana',
        'seperti': 'kek',
        'sangat': 'banget',
        'tidak': 'kagak',
        'iya': 'yoi',
        'halo': 'hai',
        'terima kasih': 'makasih',
        'maaf': 'sori',
        'tolong': 'bantuin dong',
        'sedang': 'lagi',
        'mungkin': 'kayaknya',
        'baik': 'oke',
        'benar': 'bener',
        'salah': 'salah',
        'teman': 'bro',
        'sahabat': 'bestie',
        'mengapa': 'kenapa',
        'kenapa': 'napa',
        'dimana': 'dimana',
        'kapan': 'kapan',
        'siapa': 'siapa',
        'bagaimana': 'gimana',
        'akan': 'bakal',
        'sudah': 'udah',
        'belum': 'belom',
        'juga': 'juga',
        'tetapi': 'tapi',
        'namun': 'tapi',
        'karena': 'soalnya',
        'sebab': 'gara-gara',
        'jika': 'kalo',
        'kalau': 'kalo',
        'maka': 'jadinya',
        'oleh': 'ama',
        'untuk': 'buat',
        'kepada': 'ke',
        'dari': 'dari',
        'di': 'di',
        'ke': 'ke',
        'pada': 'pas',
        'dengan': 'pake',
        'lalu': 'terus',
        'kemudian': 'abis itu',
        'sekarang': 'sekarang',
        'nanti': 'ntar',
        'besok': 'besok',
        'kemarin': 'kemaren',
        'hari ini': 'hari ini',
        'minggu ini': 'minggu ini',
        'bulan ini': 'bulan ini',
        'tahun ini': 'taun ini',
        'pernah': 'pernah',
        'selalu': 'selalu',
        'sering': 'sering',
        'jarang': 'jarang',
        'kadang-kadang': 'kadang',
        'tidak pernah': 'kagak pernah',
        'bisa': 'bisa',
        'dapat': 'bisa',
        'mampu': 'sanggup',
        'harus': 'kudu',
        'wajib': 'kudu',
        'perlu': 'perlu',
        'butuh': 'butuh',
        'ingin': 'pengen',
        'mau': 'mau',
        'boleh': 'boleh',
        'banyak': 'banyak',
        'sedikit': 'dikit',
        'semua': 'semua',
        'beberapa': 'beberapa',
        'sebagian': 'sebagian',
        'hampir': 'nyaris',
        'sekitar': 'kira-kira',
        'kurang lebih': 'kurleb',
        'lebih': 'lebih',
        'kurang': 'kurang',
        'cukup': 'cukup',
        'terlalu': 'kelewat',
        'sangat': 'banget',
        'agak': 'agak',
        'lumayan': 'lumayan',
        'suka': 'demen',
        'senang': 'seneng',
        'bahagia': 'happy',
        'sedih': 'sedih',
        'marah': 'kesel',
        'takut': 'takut',
        'benci': 'benci',
        'cinta': 'cinta',
        'sayang': 'sayang',
        'rindu': 'kangen',
        'peduli': 'peduli',
        'perhatian': 'perhatian',
        'serius': 'serius',
        'bercanda': 'bercanda',
        'tertawa': 'ketawa',
        'menangis': 'nangis',
        'tersenyum': 'senyum',
        'berbicara': 'ngomong',
        'mendengar': 'denger',
        'melihat': 'liat',
        'merasa': 'ngerasa',
        'berpikir': 'mikir',
        'mengerti': 'ngerti',
        'paham': 'paham',
        'tahu': 'tau',
        'lupa': 'lupa',
        'ingat': 'inget',
        'mencoba': 'nyoba',
        'mencari': 'nyari',
        'menemukan': 'nemuin',
        'kehilangan': 'ilang',
        'memberi': 'ngasih',
        'menerima': 'nerima',
        'mengambil': 'ngambil',
        'membawa': 'bawa',
        'mengirim': 'ngirim',
        'menjual': 'jual',
        'membeli': 'beli',
        'meminjam': 'pinjem',
        'membantu': 'bantuin',
        'menolong': 'nolongin',
        'menyelamatkan': 'nyelametin',
        'menyukai': 'suka',
        'mencintai': 'cinta',
        'membenci': 'benci',
        'menghargai': 'ngehargain',
        'menghormati': 'hormatin',
        'memaafkan': 'maafin',
        'menyalahkan': 'nyalahin',
        'mengkritik': 'ngritik',
        'memuji': 'muji',
        'menghina': 'ngehina',
        'mengejek': 'ngejek',
        'menertawakan': 'ngetawain',
        'menangisi': 'nangisin',
        'menyemangati': 'nyemangatin',
        'mendukung': 'dukung',
        'menolak': 'nolak',
        'menerima': 'nerima',
        'mengizinkan': 'ngizinin',
        'melarang': 'ngelarang',
        'menyuruh': 'nyuruh',
        'meminta': 'minta',
        'memohon': 'mohon',
        'mendesak': 'maksa',
        'memaksa': 'maksa',
        'mengajak': 'ngajak',
        'mengundang': 'ngundang',
        'menolak': 'nolak',
        'menyetujui': 'setuju',
        'menentang': 'nentang',
        'mendebat': 'debat',
        'meyakinkan': 'yakinkin',
        'meragukan': 'ragu',
        'percaya': 'percaya',
        'curiga': 'curiga',
        'menuduh': 'nuduh',
        'membela': 'bela',
        'memaklumi': 'maklum',
        'mengerti': 'ngerti',
        'memahami': 'paham',
        'mengabaikan': 'ngabaiin',
        'melupakan': 'lupain',
        'mengingat': 'inget',
        'memikirkan': 'mikirin',
        'merencanakan': 'rencanain',
        'memutuskan': 'mutusin',
        'memilih': 'milih',
        'menentukan': 'nentuin',
        'mengubah': 'ngubah',
        'memperbaiki': 'benerin',
        'merusak': 'ngerusak',
        'menghancurkan': 'ngehancurin',
        'membangun': 'bangun',
        'menciptakan': 'bikin',
        'menghasilkan': 'ngasilin',
        'menggunakan': 'pake',
        'memakai': 'pake',
        'memanfaatkan': 'manfaatin',
        'menghemat': 'ngirit',
        'membuang': 'buang',
        'menyimpan': 'nyimpen',
        'mengumpulkan': 'ngumpulin',
        'menabung': 'nabung',
        'membelanjakan': 'belanjain',
        'membayar': 'bayar',
        'menagih': 'nagih',
        'meminjam': 'pinjem',
        'mengembalikan': 'balikin',
        'memberikan': 'ngasih',
        'menerima': 'nerima',
        'menolak': 'nolak',
        'menyerahkan': 'nyerahin',
        'mengambil': 'ngambil',
        'merebut': 'rebut',
        'menemukan': 'nemuin',
        'kehilangan': 'ilang',
        'mencari': 'nyari',
        'menemukan': 'nemuin',
        'wow': 'anjay',
        'wah': 'anjir',
        'astaga': 'astagfirullah',
        'gila': 'goks',
        'keren': 'kece',
        'mantap': 'mantul',
        'santai': 'santuy',
        'serius': 'serius',
        'bercanda': 'becanda',
        'bingung': 'pusing',
        'marah': 'ngamuk',
        'bodoh': 'goblok',
        'hebat': 'jago',
        'luar biasa': 'goks',
        'teman': 'bro',
        'sahabat': 'bestie',
        'pacar': 'doi',
        'uang': 'duit',
        'makan': 'nyam',
        'tidur': 'bobo',
        'pergi': 'cabut',
        'lari': 'ngibrit',
        'cepat': 'gas',
        'lambat': 'lelet',
        'iya': 'yoi',
        'tidak': 'kagak',
        'oke': 'okeh',
        'baik': 'oke',
        'buruk': 'parah',
        'cantik': 'cakep',
        'ganteng': 'gans',
        'lucu': 'ngakak',
        'sedih': 'galau',
        'senang': 'happy',
        'takut': 'ciut',
        'malas': 'mager',
        'capek': 'cape',
        'lapar': 'laper',
        'haus': 'aus',
        'banyak': 'bejibun',
        'sedikit': 'dikit',
        'gratis': 'free',
        'mahal': 'sultan',
        'murah': 'murmer',
        'baru': 'anyar',
        'lama': 'jadul',
        'bagus': 'jos',
        'jelek': 'rombeng',
        'pintar': 'pinter',
        'bodoh': 'bego',
        'cepat': 'kilat',
        'lambat': 'siput',
        'besar': 'gede',
        'kecil': 'mungil',
        'tinggi': 'jangkung',
        'pendek': 'cebol',
        'gemuk': 'gendut',
        'kurus': 'kerempeng',
        'kaya': 'tajir',
        'miskin': 'melarat',
        'sombong': 'songong',
        'ramah': 'friendly',
        'jahat': 'jahanam',
        'baik': 'alim',
        'nakal': 'bandel',
        'rajin': 'tekun',
        'malas': 'males',
        'berani': 'jagoan',
        'penakut': 'cupu',
        'jujur': 'polos',
        'bohong': 'hoax',
        'cinta': 'cinta',
        'benci': 'dendam',
        'suka': 'demen',
        'tidak suka': 'ogah',
        'senang': 'happy',
        'sedih': 'mewek',
        'marah': 'ngamuk',
        'takut': 'ciut',
        'malu': 'malu-malu kucing',
        'bangga': 'pede',
        'kecewa': 'bete',
        'bosan': 'bete',
        'lelah': 'capek',
        'semangat': 'semangat 45',
        'stress': 'puyeng',
        'santai': 'slow',
        'terburu-buru': 'kebut-kebutan',
        'bingung': 'pusing',
        'panik': 'panik',
        'tenang': 'adem ayem',
        'gugup': 'deg-degan',
        'percaya diri': 'pede',
        'ragu-ragu': 'galau',
        'yakin': 'yakin',
        'tidak yakin': 'ragu',
        'setuju': 'gas',
        'tidak setuju': 'ogah',
        'mengerti': 'ngeh',
        'tidak mengerti': 'gak ngeh',
        'tahu': 'tau',
        'tidak tahu': 'gak tau',
        'ingat': 'inget',
        'lupa': 'lupa',
        'berpikir': 'mikir',
        'bermimpi': 'ngayal',
        'berharap': 'berharap',
        'putus asa': 'hopeless',
        'optimis': 'pede',
        'pesimis': 'minder',
        'percaya': 'percaya',
        'curiga': 'curiga',
        'cemburu': 'jealous',
        'iri': 'sirik',
        'kagum': 'terpesona',
        'kecewa': 'kecewa',
        'menyesal': 'nyesel',
        'memaafkan': 'maafin',
        'dendam': 'dendam',
        'bahagia': 'bahagia',
        'sedih': 'sedih',
        'tertawa': 'ngakak',
        'menangis': 'nangis',
        'tersenyum': 'senyum',
        'cemberut': 'manyun',
        'melamun': 'bengong',
        'berteriak': 'teriak',
        'berbisik': 'bisik-bisik',
        'diam': 'diem',
        'berisik': 'brisik',
        'ribut': 'rame',
        'tenang': 'adem ayem',
        'ramai': 'rame',
        'sepi': 'sepi',
        'bersemangat': 'semangat',
        'lesu': 'loyo',
        'bersinar': 'cerah',
        'suram': 'mendung',
        'indah': 'cakep',
        'jelek': 'ancur',
        'menarik': 'menarik',
        'membosankan': 'boring',
        'menyenangkan': 'seru',
        'menyebalkan': 'nyebelin',
        'mengasyikkan': 'asyik',
        'mengerikan': 'serem',
        'menakutkan': 'ngeri',
        'menjijikkan': 'jijay',
        'menyedihkan': 'miris',
        'mengharukan': 'mewek',
        'menggembirakan': 'happy',
        'mengecewakan': 'zonk',
        'mengejutkan': 'shocking',
        'mengagetkan': 'kaget',
        'melegakan': 'lega',
        'menenangkan': 'tenang',
        'menyegarkan': 'seger',
        'melelahkan': 'capek',
        'menyakitkan': 'sakit',
        'menyembuhkan': 'sembuh',
        'memuaskan': 'puas',
        'mengecewakan': 'kecewa',
        'membahagiakan': 'bahagia',
        'menyedihkan': 'sedih',
        'menyenangkan': 'senang',
        'membosankan': 'bosen',
        'menarik': 'menarik',
        'membingungkan': 'bingung',
        'meyakinkan': 'yakin',
        'meragukan': 'ragu',
        'mempercayai': 'percaya',
        'mencurigai': 'curiga',
        'mengagumi': 'kagum',
        'membenci': 'benci',
        'mencintai': 'cinta',
        'menyukai': 'suka',
        'tidak suka': 'gak suka',
        'menghargai': 'hargai',
        'meremehkan': 'remeh',
        'menghormati': 'hormat',
        'merendahkan': 'rendah',
        'membanggakan': 'bangga',
        'mempermalukan': 'malu',
        'memaafkan': 'maaf',
        'menyalahkan': 'salah',
        'membenarkan': 'benar',
        'menyetujui': 'setuju',
        'menolak': 'tolak',
        'menerima': 'terima',
        'mengerti': 'ngerti',
        'tidak mengerti': 'gak ngerti',
        'memahami': 'paham',
        'tidak paham': 'gak paham',
        'mengingat': 'ingat',
        'melupakan': 'lupa',
        'memikirkan': 'pikir',
        'mengabaikan': 'abaikan',
        'memperhatikan': 'perhatikan',
        'mengabaikan': 'abaikan',
        'menyadari': 'sadar',
        'tidak sadar': 'gak sadar',
        'mengetahui': 'tahu',
        'tidak tahu': 'gak tahu',
        'mempelajari': 'belajar',
        'mengajarkan': 'ajar',
        'memahami': 'paham',
        'tidak paham': 'gak paham',
        'menguasai': 'kuasai',
        'tidak menguasai': 'gak kuasai',
        'menyelesaikan': 'selesai',
        'gagal': 'gagal',
        'berhasil': 'berhasil',
        'mencoba': 'coba',
        'menyerah': 'nyerah',
        'berjuang': 'juang',
        'berusaha': 'usaha',
        'berhenti': 'stop',
        'melanjutkan': 'lanjut',
        'memulai': 'mulai',
        'mengakhiri': 'akhir',
        'menunda': 'tunda',
        'mempercepat': 'cepat',
        'memperlambat': 'lambat',
        'meningkatkan': 'tingkat',
        'menurunkan': 'turun',
        'memperbaiki': 'baik',
        'merusak': 'rusak',
        'memperkuat': 'kuat',
        'melemahkan': 'lemah',
        'memperbesar': 'besar',
        'memperkecil': 'kecil',
        'memperpanjang': 'panjang',
        'memperpendek': 'pendek',
        'memperluas': 'luas',
        'mempersempit': 'sempit',
        'memperdalam': 'dalam',
        'memperdangkal': 'dangkal',
        'mempertinggi': 'tinggi',
        'memperendah': 'rendah',
        'mempercantik': 'cantik',
        'memperburuk': 'buruk',
        'memperbaharui': 'baru',
        'memperbarui': 'baru',
        'mempermodern': 'modern',
        'memperkuno': 'kuno',
        'memperindah': 'indah',
        'memperjelek': 'jelek',
        'mempermudah': 'mudah',
        'mempersulit': 'sulit',
        'mempercepat': 'cepat',
        'memperlambat': 'lambat',
        'mempertebal': 'tebal',
        'mempertipis': 'tipis',
        'memperkeras': 'keras',
        'memperlunak': 'lunak',
        'memperhalus': 'halus',
        'memperkasar': 'kasar',
        'memperkuat': 'kuat',
        'memperlemah': 'lemah',
        'memperbanyak': 'banyak',
        'mempersedikit': 'sedikit',
        'memperberat': 'berat',
        'memperingan': 'ringan',
        'memperpanjang': 'panjang',
        'memperpendek': 'pendek',
        'memperlebar': 'lebar',
        'mempersempit': 'sempit',
        'mempertinggi': 'tinggi',
        'memperendah': 'rendah',
        'memperdalam': 'dalam',
        'memperdangkal': 'dangkal'
    };

    return text.toLowerCase().split(' ').map(word => 
        gaulDict[word] || word
    ).join(' ');
}

function isAskingAboutCreator(message, language = 'id') {
    const lowerMessage = message.toLowerCase();
    const creatorKeywords = {
        'id': ['siapa pembuat', 'siapa yang membuat', 'siapa yang menciptakan', 'siapa penciptamu', 'siapa yang bikin', 'siapa creator'],
        'en': ['who created', 'who made', 'who is your creator', 'who developed you', 'who is your developer', 'who built you'],
    };

    return (creatorKeywords[language] || []).some(keyword => lowerMessage.includes(keyword));
}

function replaceEmojis(text, language = 'id') {
    // Jika Anda ingin mempertahankan emoji asli, cukup kembalikan teks tanpa perubahan
    return text;

    // Jika di masa depan Anda ingin menambahkan deskripsi emoji tanpa menghapus emoji asli,
    // Anda bisa menggunakan kode seperti ini:
    /*
    const emojiMap = {
        'id': {
            '😎': '😎 (Emot Kece Mek)',
            '😊': '😊 (Emot Senyum)',
            '🤔': '🤔 (Emot Mikir)',
        },
        'en': {
            '😎': '😎 (Cool Emoji)',
            '😊': '😊 (Smiling Emoji)',
            '🤔': '🤔 (Thinking Emoji)',
        },
    };

    const languageMap = emojiMap[language] || emojiMap['en'];

    return text.replace(/[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{1F1E0}-\u{1F1FF}]/gu, (match) => {
        return languageMap[match] || match;
    });
    */
}

exports.replaceEmojis = replaceEmojis;

// Tambahkan fungsi baru ini
function addCreatorInfo(text, userMessage, language = 'id') {
    // Hanya tambahkan info jika belum ada referensi ke AETHER
    if (!text.toLowerCase().includes('aether')) {
        const creatorInfo = {
            'id': "Oh, ngomong-ngomong soal AETHER, dia tuh yang bikin gue. ",
            'en': "Oh, by the way, AETHER is the one who created me. "
        };
        return text + " " + (creatorInfo[language] || creatorInfo['en']);
    }
    return text;
}

// Modifikasi fungsi getAIResponse
exports.getAIResponse = async (pesan, history = [], language = 'id') => {
    try {
        if (isAskingAboutCreator(pesan, language)) {
            const creatorResponse = language === 'id' 
                ? "Gue dibikin sama AETHER mek!, Dia tuh yang bikin gue jadi A-I keren kayak begini. 😎"
                : "I was created by AETHER! They're the one who made me this cool AI. 😎";
            return creatorResponse;
        }

        console.log('Sending request to:', config.aiApiUrl);
        
        const context = history.map(msg => `${msg.role}: ${msg.content}`).join('\n');
        const fullPrompt = `${context}\nUser: ${pesan}\nAI:`;
        
        console.log('Request payload:', { prompt: fullPrompt });
        
        const response = await axios.get(`${config.aiApiUrl}?prompt=${encodeURIComponent(fullPrompt)}`);
        
        console.log('Response received:', response.data);
        
        if (response.data) {
            let aiResponse = response.data;
            // Hanya tambahkan info tentang AETHER jika belum ada dalam respons
            if (!aiResponse.toLowerCase().includes('aether')) {
                aiResponse = toGaul(aiResponse, language);
            }
            return aiResponse;
        } else {
            throw new Error('Format respons dari layanan AI tidak sesuai');
        }
    } catch (error) {
        console.error('Kesalahan pada layanan AI:', error.message);
        if (error.response) {
            console.error('Status respons:', error.response.status);
            console.error('Data respons:', error.response.data);
        }
        return language === 'id' 
            ? 'Waduh, error nih bro. Coba lagi ntar ya! 😅'
            : 'Oops, there was an error. Please try again later! 😅';
    }
};

